### ISSUE TITLE
Add User-friendly Errors for effective feedback

### ISSUE THREAD

**Issue by submetu** [IvenProductCloud/nodejsSDK#1]
When there's any sort of error (user or server), the SDK responds with a number **0**.

This can be enhanced by returning the user readable errors so that they could know whether they made a mistake or whether the cloud server is not responding. If the user made a mistake, they will know what mistake they are making.

This could help people who are not familiar with the SKD's code itself.

I could not make a pull request since I don't have the permissions. I forked the repository and made some changes and adjusted the MOCHA tests accordingly to pass. 

Please have a look at the **index.js** and **test/unittests.js** files your spare time.

Visit the forked repository at https://github.com/submetu/nodejsSDK to see the files.

**Comment by BerkOzdilek** [comment]
Thanks for the feedback. Your fork has been merged.
